name: Test Simple Bank
on:
  push:
    - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_DB: simple_bank
          POSTGRES_PASSWORD: secret
          POSTGRES_USER: root
        ports:
          - 49466:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.0'
      - name: Install migrate library
        run: |
          make install-migrate
          sudo mv migrate /usr/bin/
          which migrate 
      - name: Run migration
        run: make migrateup
      - name: Test
        run: make test
